#cloud-config
##apt_upgrade: True
##apt_reboot_if_required: False
packages:
  - python3-prometheus-client
  - python3-flask
  - mariadb-server
  - unzip
  - git
  - dirmngr
  - gpg
  - curl
  - wget
  - gawk
users:
  - name: root
    lock-passwd: false
    plain_text_passwd: "TrainingDay"
ssh_pwauth: True ## This line enables ssh password authentication
runcmd:
  - ufw disable
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin yes/' /etc/ssh/sshd_config
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - restart ssh
## DB data
  - cd /home && wget "https://github.com/pragmatic-fermat/observabilite_des_applications/blob/main/data/mysqlsampledatabase.zip" && unzip /home/mysqlsampledatabase.zip
## asdf  
  - cd /root && git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0
  - echo '. "$HOME/.asdf/asdf.sh"' >> /root/.bashrc
  - echo '. "$HOME/.asdf/completions/asdf.bash"' >> /root/.bashrc
  - asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git && asdf install
snap:
    commands:
        00: ['install', 'yq']
        01: ['install', 'kubectl', '--classic']
        02: ['install', 'helm', '--classic']
